version: 2

sources:
  - name: dbt_bq_public_datasets
    database: bigquery-public-data
    schema: cms_synthetic_patient_data_omop
    tables:
      - name: person
        freshness: null
      - name: care_site
        freshness: null
      - name: location
        freshness: null
      - name: concept
        freshness: null  
      - name: observation
        freshness: null  