
CMS_OMOP:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: your-project-id
      dataset: your-dataset
      keyfile: /path/to/service-account.json
